{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "7621fd93-28b0-4f63-b360-6c7d6b715510",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\poova\\anaconda3\\lib\\site-packages (1.51.0)\n",
      "Requirement already satisfied: pandas in c:\\users\\poova\\anaconda3\\lib\\site-packages (2.3.3)\n",
      "Requirement already satisfied: numpy in c:\\users\\poova\\anaconda3\\lib\\site-packages (2.3.5)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\poova\\anaconda3\\lib\\site-packages (1.7.2)\n",
      "Requirement already satisfied: matplotlib in c:\\users\\poova\\anaconda3\\lib\\site-packages (3.10.6)\n",
      "Requirement already satisfied: seaborn in c:\\users\\poova\\anaconda3\\lib\\site-packages (0.13.2)\n",
      "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (5.5.0)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<7,>=4.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (5.5.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (8.2.1)\n",
      "Requirement already satisfied: packaging<26,>=20 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (25.0)\n",
      "Requirement already satisfied: pillow<13,>=7.1.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (12.0.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (5.29.3)\n",
      "Requirement already satisfied: pyarrow<22,>=7.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (21.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (2.32.5)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (9.1.2)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (4.15.0)\n",
      "Requirement already satisfied: watchdog<7,>=2.1.5 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (4.0.2)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (3.1.45)\n",
      "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from streamlit) (6.5.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)\n",
      "Requirement already satisfied: narwhals>=1.14.2 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\poova\\anaconda3\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.11)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2026.5.20)\n",
      "Requirement already satisfied: scipy>=1.8.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from scikit-learn) (1.16.3)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from scikit-learn) (1.5.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from scikit-learn) (3.5.0)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from matplotlib) (1.3.3)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from matplotlib) (4.60.1)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from matplotlib) (1.4.9)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from matplotlib) (3.2.5)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\poova\\anaconda3\\lib\\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install streamlit pandas numpy scikit-learn matplotlib seaborn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5f3f9147-b490-407f-b00f-13d06115b7df",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-06-03 23:23:16.523 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.525 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.528 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.530 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.532 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.535 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.541 No runtime found, using MemoryCacheStorageManager\n",
      "2026-06-03 23:23:16.555 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.561 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.567 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.570 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.610 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.613 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.616 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.620 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.623 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.633 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.651 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.654 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.657 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.661 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.663 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.670 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.674 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.677 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.683 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.685 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.702 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.711 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.716 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.720 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.725 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.727 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.748 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.753 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.758 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.763 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.765 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.769 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.774 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.796 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.798 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.801 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.803 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.806 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:16.808 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:17.030 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:18.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:18.670 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:18.672 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:18.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:18.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:18.682 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:18.685 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:18.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:18.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:19.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:19.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:19.503 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:19.505 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:19.508 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:19.511 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.339 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.401 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.415 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:20.608 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:28.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:28.792 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:28.795 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:36.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:36.051 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:36.054 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:44.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:44.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:44.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:52.016 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:52.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:52.021 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:59.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:59.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:23:59.819 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:07.328 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:07.329 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:07.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:11.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:11.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:11.485 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:16.177 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:16.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:16.180 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:20.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:20.732 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:20.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.160 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.163 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.171 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.172 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.174 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.175 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.179 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-06-03 23:24:25.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.184 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.185 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.187 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.189 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.189 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.191 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.192 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.297 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.940 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.942 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-03 23:24:25.943 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.metrics import accuracy_score, classification_report, brier_score_loss\n",
    "\n",
    "# Set page configuration\n",
    "st.set_page_config(page_title=\"TN Election Analytics Dashboard\", layout=\"wide\")\n",
    "\n",
    "st.title(\"🗳️ Tamil Nadu Election Analytics & Predictive Engine\")\n",
    "st.markdown(\"Analyze the 2026 ECI election results and simulate future electoral shifts using Machine Learning.\")\n",
    "\n",
    "# ==========================================\n",
    "# CONSTANTS & UTILITIES\n",
    "# ==========================================\n",
    "FILE_NAME = 'eci_results_tamilnadu_2026.csv'\n",
    "\n",
    "def categorize_party(party):\n",
    "    if 'Dravida Munnetra Kazhagam' in party and 'All India' not in party: return 'DMK'\n",
    "    elif 'All India Anna Dravida Munnetra Kazhagam' in party: return 'AIADMK'\n",
    "    elif 'Naam Tamilar Katchi' in party: return 'NTK'\n",
    "    elif 'Tamilaga Vettri Kazhagam' in party: return 'TVK'\n",
    "    elif 'Independent' in party: return 'Independent'\n",
    "    else: return 'Others'\n",
    "\n",
    "@st.cache_data\n",
    "def load_and_preprocess_data():\n",
    "    df = pd.read_csv(FILE_NAME)\n",
    "    df['Party_Cat'] = df['Party'].apply(categorize_party)\n",
    "    \n",
    "    # Calculate Constituency Totals and Vote Shares\n",
    "    const_totals = df.groupby('Constituency')['Total Votes'].sum().reset_index()\n",
    "    const_totals.columns = ['Constituency', 'Const_Total_Votes']\n",
    "    df = df.merge(const_totals, on='Constituency')\n",
    "    df['Baseline_Vote_Share'] = df['Total Votes'] / df['Const_Total_Votes']\n",
    "    \n",
    "    # Tag 2026 Winners\n",
    "    df['Is_Winner_2026'] = 0\n",
    "    idx = df.groupby('Constituency')['Total Votes'].idxmax()\n",
    "    df.loc[idx, 'Is_Winner_2026'] = 1\n",
    "    return df\n",
    "\n",
    "# Load the data safely\n",
    "try:\n",
    "    df = load_and_preprocess_data()\n",
    "except FileNotFoundError:\n",
    "    st.error(f\"Could not find the file verbatim named '{FILE_NAME}'. Please make sure it is in the same directory.\")\n",
    "    st.stop()\n",
    "\n",
    "# ==========================================\n",
    "# SIDEBAR CONTROLS\n",
    "# ==========================================\n",
    "st.sidebar.header(\"🛠️ Simulation Controls\")\n",
    "st.sidebar.markdown(\"Adjust political swing percentages for the **Next Election**:\")\n",
    "\n",
    "swing_dmk = st.sidebar.slider(\"DMK Swing (%)\", -10.0, 10.0, 2.0, step=0.5) / 100.0\n",
    "swing_aiadmk = st.sidebar.slider(\"AIADMK Swing (%)\", -10.0, 10.0, -1.0, step=0.5) / 100.0\n",
    "swing_tvk = st.sidebar.slider(\"TVK Swing (%)\", -10.0, 10.0, -2.0, step=0.5) / 100.0\n",
    "swing_ntk = st.sidebar.slider(\"NTK Swing (%)\", -10.0, 10.0, 1.0, step=0.5) / 100.0\n",
    "swing_others = st.sidebar.slider(\"Others Swing (%)\", -10.0, 10.0, 0.0, step=0.5) / 100.0\n",
    "\n",
    "n_sims = st.sidebar.number_input(\"Monte Carlo Iterations\", min_value=100, max_value=2000, value=500, step=100)\n",
    "volatility = st.sidebar.slider(\"Constituency Volatility (Noise SD)\", 1.0, 10.0, 3.5, step=0.5) / 100.0\n",
    "\n",
    "future_swings = {\n",
    "    'DMK': swing_dmk, 'AIADMK': swing_aiadmk, 'TVK': swing_tvk, 'NTK': swing_ntk, 'Others': swing_others, 'Independent': 0.0\n",
    "}\n",
    "\n",
    "# ==========================================\n",
    "# TABS BACKBONE\n",
    "# ==========================================\n",
    "tab1, tab2, tab3 = st.tabs([\"📊 2026 Baseline & Visualization\", \"🤖 ML Model Validation\", \"🔮 Next Election Predictor\"])\n",
    "\n",
    "# ------------------------------------------\n",
    "# TAB 1: 2026 BASELINE\n",
    "# ------------------------------------------\n",
    "with tab1:\n",
    "    st.header(\"Actual 2026 Election Summary\")\n",
    "    \n",
    "    # Metrics\n",
    "    winners_2026 = df[df['Is_Winner_2026'] == 1]['Party_Cat'].value_counts()\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    col1.metric(\"TVK Seats (2026)\", int(winners_2026.get('TVK', 0)))\n",
    "    col2.metric(\"DMK Seats (2026)\", int(winners_2026.get('DMK', 0)))\n",
    "    col3.metric(\"AIADMK Seats (2026)\", int(winners_2026.get('AIADMK', 0)))\n",
    "    col4.metric(\"Total Constituencies\", int(df['Constituency'].nunique()))\n",
    "    \n",
    "    st.subheader(\"Data Scattering: EVM Votes vs Vote Share Percentage\")\n",
    "    sns.set_theme(style=\"whitegrid\")\n",
    "    fig, ax = plt.subplots(figsize=(10, 5))\n",
    "    sns.scatterplot(\n",
    "        data=df, \n",
    "        x='EVM Votes', \n",
    "        y='% Votes', \n",
    "        hue='Is_Winner_2026', \n",
    "        palette={0: '#34495e', 1: '#e74c3c'}, \n",
    "        alpha=0.7, \n",
    "        style='Is_Winner_2026',\n",
    "        markers={0: 'o', 1: 'X'},\n",
    "        s=80,\n",
    "        ax=ax\n",
    "    )\n",
    "    plt.title('Distribution of Candidates: EVM Votes vs Vote %', fontsize=12)\n",
    "    plt.xlabel('EVM Votes')\n",
    "    plt.ylabel('Percentage of Votes (%)')\n",
    "    st.pyplot(fig)\n",
    "\n",
    "# ------------------------------------------\n",
    "# TAB 2: ML MODEL VALIDATION\n",
    "# ------------------------------------------\n",
    "with tab2:\n",
    "    st.header(\"Classifier Performance Analysis\")\n",
    "    st.markdown(\"This tab evaluates the machine learning model's historical ability to isolate winners based on numeric voting strengths.\")\n",
    "    \n",
    "    # Feature engineering for classification\n",
    "    le = LabelEncoder()\n",
    "    df['Party_Encoded'] = le.fit_transform(df['Party_Cat'])\n",
    "    \n",
    "    X = df[['Party_Encoded', 'EVM Votes', 'Postal Votes']]\n",
    "    y = df['Is_Winner_2026']\n",
    "    \n",
    "    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)\n",
    "    \n",
    "    rf = RandomForestClassifier(random_state=42, n_estimators=100)\n",
    "    rf.fit(X_train, y_train)\n",
    "    y_pred = rf.predict(X_test)\n",
    "    \n",
    "    acc = accuracy_score(y_test, y_pred)\n",
    "    \n",
    "    col_m1, col_m2 = st.columns(2)\n",
    "    col_m1.metric(\"Random Forest Classification Accuracy\", f\"{acc*100:.2f}%\")\n",
    "    \n",
    "    # Brier Score\n",
    "    df['Historical_Noise_Estimate'] = df['Baseline_Vote_Share'] + np.random.normal(0, 0.04, len(df))\n",
    "    df['Prob_Norm'] = df.groupby('Constituency')['Historical_Noise_Estimate'].transform(lambda x: x.clip(0) / (x.clip(0).sum() + 1e-9))\n",
    "    brier = brier_score_loss(df['Is_Winner_2026'], df['Prob_Norm'])\n",
    "    col_m2.metric(\"Probability Calibration (Brier Score)\", f\"{brier:.4f}\", help=\"Closer to 0.0 is perfect.\")\n",
    "    \n",
    "    st.subheader(\"Classification Matrix Report\")\n",
    "    report_dict = classification_report(y_test, y_pred, output_dict=True, target_names=['Lost', 'Won'])\n",
    "    st.table(pd.DataFrame(report_dict).transpose())\n",
    "\n",
    "# ------------------------------------------\n",
    "# TAB 3: NEXT ELECTION PREDICTOR\n",
    "# ------------------------------------------\n",
    "with tab3:\n",
    "    st.header(\"Monte Carlo Future Election Forecasting\")\n",
    "    st.markdown(\"Running real-time chaotic simulations based on your custom sidebar configurations:\")\n",
    "    \n",
    "    simulated_tallies = []\n",
    "    \n",
    "    # Progress indicator\n",
    "    progress_bar = st.progress(0)\n",
    "    \n",
    "    for sim in range(n_sims):\n",
    "        sim_df = df[['Constituency', 'Party_Cat', 'Baseline_Vote_Share']].copy()\n",
    "        sim_df['Shifted'] = sim_df.apply(lambda r: r['Baseline_Vote_Share'] + future_swings.get(r['Party_Cat'], 0), axis=1)\n",
    "        \n",
    "        # Inject random Gaussian disturbance matrix\n",
    "        noise = np.random.normal(0, volatility, size=len(sim_df))\n",
    "        sim_df['Simulated_Share'] = (sim_df['Shifted'] + noise).clip(lower=0)\n",
    "        \n",
    "        # Tally localized highest share metrics\n",
    "        win_idx = sim_df.groupby('Constituency')['Simulated_Share'].idxmax()\n",
    "        winners = sim_df.loc[win_idx, 'Party_Cat'].value_counts().to_dict()\n",
    "        simulated_tallies.append(winners)\n",
    "        \n",
    "        # Update progress dynamically\n",
    "        if sim % (max(1, n_sims // 10)) == 0:\n",
    "            progress_bar.progress(int((sim / n_sims) * 100))\n",
    "            \n",
    "    progress_bar.progress(100)\n",
    "    \n",
    "    # Build results frame\n",
    "    res_df = pd.DataFrame(simulated_tallies).fillna(0)\n",
    "    \n",
    "    # Final Presentation Table\n",
    "    summary_data = []\n",
    "    for party in ['TVK', 'DMK', 'AIADMK', 'NTK', 'Others']:\n",
    "        if party in res_df.columns:\n",
    "            series = res_df[party]\n",
    "            summary_data.append({\n",
    "                \"Party Group\": party,\n",
    "                \"Expected Average Seats\": round(series.mean(), 1),\n",
    "                \"95% Confidence Interval\": f\"[{int(np.percentile(series, 2.5))} to {int(np.percentile(series, 97.5))}]\"\n",
    "            })\n",
    "            \n",
    "    summary_df = pd.DataFrame(summary_data)\n",
    "    \n",
    "    col_t1, col_t2 = st.columns([1, 2])\n",
    "    \n",
    "    with col_t1:\n",
    "        st.subheader(\"Expected Seat Share Predictions\")\n",
    "        st.dataframe(summary_df, use_container_width=True)\n",
    "        st.caption(\"ℹ️ Majority Mark is 118 seats.\")\n",
    "        \n",
    "    with col_t2:\n",
    "        st.subheader(\"Probability Distributions\")\n",
    "        fig2, ax2 = plt.subplots(figsize=(10, 5))\n",
    "        for party in ['TVK', 'DMK', 'AIADMK']:\n",
    "            if party in res_df.columns:\n",
    "                sns.kdeplot(res_df[party], label=party, fill=True, alpha=0.3, ax=ax2)\n",
    "        plt.axvline(118, color='red', linestyle='--', label='Majority Mark (118)')\n",
    "        plt.title('Frequency Array Curve of Seats Won Across Simulations')\n",
    "        plt.xlabel('Seats Tally')\n",
    "        plt.ylabel('Density Probability Matrix')\n",
    "        plt.legend()\n",
    "        st.pyplot(fig2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f7ceff17-ade5-4e50-a78c-920ef3b61cdc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
